improvement

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -3,7 +3,7 @@
 STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")
 
 if [[ "$STAGED_GO_FILES" = "" ]]; then
-  exit 0
+ exit 0
 fi
 
 GOLANGCI_LINT=$GOPATH/bin/golangci-lint
@@ -11,14 +11,14 @@ GOLINES=$GOPATH/bin/golines
 
 # Check for golangci-lint
 if [[ ! -x "$GOLANGCI_LINT" ]]; then
-  printf "\t\033[41mPlease install golangci-lint (go install github.com/golangci/golangci-lint/cmd/golangci-lint)"
-  exit 1
+ printf "\t\033[41mPlease install golangci-lint (go install github.com/golangci/golangci-lint/cmd/golangci-lint)"
+ exit 1
 fi
 
 # Check for golines
 if [[ ! -x "$GOLINES" ]]; then
-  printf "\t\033[41mPlease install golines (go install github.com/segmentio/golines@latest)"
-  exit 1
+ printf "\t\033[41mPlease install golines (go install github.com/segmentio/golines@latest)"
+ exit 1
 fi
 
 NORMAL=$(tput sgr0)
@@ -26,30 +26,26 @@ LIME_YELLOW=$(tput setaf 190)
 RED=$(tput setaf 1)
 GREEN=$(tput setaf 2)
 
-printf "${LIME_YELLOW}Running go fmt on all staged *.go files...${NORMAL}\n"
-go fmt ./...
-if [[ $? != 0 ]]; then
-  printf "${RED}Linting failed! ${NORMAL}Please fix errors before committing.\n"
-  exit 1
-else
- printf "${GREEN}Linting passed! ${NORMAL}Continuing to commit.\n"
-fi
-printf "${LIME_YELLOW}Running golines on all staged *.go files...${NORMAL}\n"
-golines . -m 120 -w
+for FILE in $STAGED_GO_FILES
+do
+  printf "${LIME_YELLOW}Running go fmt on $FILE...${NORMAL}\n"
+  go fmt $FILE
+  if [[ $? != 0 ]]; then
+   printf "${RED}Linting failed! ${NORMAL}Please fix errors before committing.\n"
+   exit 1
+  else
+   printf "${GREEN}Linting passed! ${NORMAL}Continuing to commit.\n"
+  fi
 
-if [[ $? != 0 ]]; then
-  printf "${RED}Linting failed! ${NORMAL}Please fix errors before committing.\n"
-  exit 1
-else
- printf "${GREEN}Linting passed! ${NORMAL}Continuing to commit.\n"
-fi
+  printf "${LIME_YELLOW}Running golines on $FILE...${NORMAL}\n"
+  golines $FILE -m 120 -w
+  if [[ $? != 0 ]]; then
+   printf "${RED}Linting failed! ${NORMAL}Please fix errors before committing.\n"
+   exit 1
+  else
+   printf "${GREEN}Linting passed! ${NORMAL}Continuing to commit.\n"
+  fi
+done
 
 printf "${LIME_YELLOW}Running golangci-lint on all staged *.go files...${NORMAL}\n"
-golangci-lint run
-
-if [[ $? != 0 ]]; then
-  printf "${RED}Linting failed! ${NORMAL}Please fix errors before committing.\n"
-  exit 1
-else
- printf "${GREEN}Linting passed! ${NORMAL}Continuing to commit.\n"
-fi
+golangci-lint run $STAGED_GO_FILES
