test tunnel

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -3,7 +3,7 @@
 STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")
 
 if [[ "$STAGED_GO_FILES" = "" ]]; then
- exit 0
+  exit 0
 fi
 
 GOLANGCI_LINT=$GOPATH/bin/golangci-lint
@@ -11,14 +11,14 @@ GOLINES=$GOPATH/bin/golines
 
 # Check for golangci-lint
 if [[ ! -x "$GOLANGCI_LINT" ]]; then
- printf "\t\033[41mPlease install golangci-lint (go install github.com/golangci/golangci-lint/cmd/golangci-lint)"
- exit 1
+  printf "\t\033[41mPlease install golangci-lint (go install github.com/golangci/golangci-lint/cmd/golangci-lint)"
+  exit 1
 fi
 
 # Check for golines
 if [[ ! -x "$GOLINES" ]]; then
- printf "\t\033[41mPlease install golines (go install github.com/segmentio/golines@latest)"
- exit 1
+  printf "\t\033[41mPlease install golines (go install github.com/segmentio/golines@latest)"
+  exit 1
 fi
 
 NORMAL=$(tput sgr0)
@@ -31,21 +31,31 @@ do
   printf "${LIME_YELLOW}Running go fmt on $FILE...${NORMAL}\n"
   go fmt $FILE
   if [[ $? != 0 ]]; then
-   printf "${RED}Linting failed! ${NORMAL}Please fix errors before committing.\n"
-   exit 1
+    printf "${RED}Linting failed! ${NORMAL}Please fix errors before committing.\n"
+    exit 1
   else
-   printf "${GREEN}Linting passed! ${NORMAL}Continuing to commit.\n"
+    printf "${GREEN}Linting passed! ${NORMAL}Continuing to commit.\n"
   fi
 
   printf "${LIME_YELLOW}Running golines on $FILE...${NORMAL}\n"
   golines $FILE -m 120 -w
   if [[ $? != 0 ]]; then
-   printf "${RED}Linting failed! ${NORMAL}Please fix errors before committing.\n"
-   exit 1
+    printf "${RED}Linting failed! ${NORMAL}Please fix errors before committing.\n"
+    exit 1
   else
-   printf "${GREEN}Linting passed! ${NORMAL}Continuing to commit.\n"
+    printf "${GREEN}Linting passed! ${NORMAL}Continuing to commit.\n"
   fi
 done
 
-printf "${LIME_YELLOW}Running golangci-lint on all staged *.go files...${NORMAL}\n"
-golangci-lint run $STAGED_GO_FILES
+DIRS=$(dirname $STAGED_GO_FILES | sort -u)
+for DIR in $DIRS
+do
+  printf "${LIME_YELLOW}Running golangci-lint on $DIR...${NORMAL}\n"
+  golangci-lint run $DIR
+  if [[ $? != 0 ]]; then
+    printf "${RED}Linting failed! ${NORMAL}Please fix errors before committing.\n"
+    exit 1
+  else
+    printf "${GREEN}Linting passed! ${NORMAL}Continuing to commit.\n"
+  fi
+done
